[build]
  command = "npx prisma db push --skip-generate && npx tsx prisma/seed.ts && npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
